FROM python:3.11-slim
WORKDIR /app

# Install OS dependencies yang dibutuhkan aiohttp & library lain
RUN apt-get update && apt-get install -y \
    build-essential \
    libffi-dev \
    libssl-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src

CMD ["python", "src/app.py", "--id", "node1"]
